FROM blackarchlinux/blackarch:latest

MAINTAINER s.takoor <https://github.com/s-takoor>

ENV TERM xterm-256color

# minor tweaks to pacman.conf
RUN sed -i "s/#Color/Color/" /etc/pacman.conf && \
    sed -i "/^Color/a ILoveCandy" /etc/pacman.conf && \
    sed -i "s/NoProgressBar/#NoProgressBar/" /etc/pacman.conf && \
    sed -i "s/VerbosePkgLists/#VerbosePkgLists/" /etc/pacman.conf && \
    pacman -Syyu --noconfirm

# essential packages
RUN \
    pacman -Syu --noconfirm \
    amass \
    bat \
    binwalk \
    cewl \
    ctags \
    crackmapexec \
    dirb \
    enum4linux-ng \
    exa \
    fd \
    ffuf \
    fzf \
    git \
    gobuster \
    hashcat \
    htop \
    hydra \
    john \
    jwt-tool \
    kiterunner \
    linenum \
    masscan \
    metasploit \
    neovim \
    nosqlmap \
    nikto \
    nmap \
    nuclei \
    nuclei-templates \
    openssh \
    p7zip \
    peass \
    perl-image-exiftool \
    python \
    recon-ng \
    responder \
    ripgrep \
    seclists \
    smbclient \
    sqlmap \
    steghide \
    subfinder \
    sublist3r \
    tcpdump \
    tmux \
    tree \
    ttf-iosevka-nerd \
    unzip \
    wfuzz \
    wget \
    whatweb \
    whois \
    wpscan \
    xsstrike \
    zsh \
    zoxide

# timezone
RUN \
    ln -sf /usr/share/zoneinfo/Indian/Mauritius /etc/localtime

# exploit-db
RUN \
    git clone https://gitlab.com/exploit-database/exploitdb.git /opt/exploitdb && \
    ln -sf /opt/exploitdb/searchsploit /sbin/searchsploit

# custom shell
COPY shell/ /tmp
RUN \
    cat /tmp/zshrc >> /root/.zshrc
